"""Markdown generator for program information."""
from pathlib import Path
from abm_check.domain.models import Program


class MarkdownGenerator:
    """Generate Markdown files for program information."""
    
    def generate_program_md(self, program: Program) -> str:
        """
        Generate Markdown content for a program.
        
        Args:
            program: Program object
            
        Returns:
            Markdown formatted string
        """
        lines = []
        
        # Title
        lines.append(f"# {program.title}\n")
        
        # Program info
        lines.append("## 番組情報\n")
        lines.append(f"- **番組ID**: {program.id}")
        lines.append(f"- **URL**: {program.url}")
        lines.append(f"- **総エピソード数**: {program.total_episodes}")
        lines.append(f"- **最新話**: 第{program.latest_episode_number}話")
        lines.append(f"- **取得日時**: {program.fetched_at.strftime('%Y/%m/%d %H:%M:%S')}\n")
        
        # Thumbnail
        if program.thumbnail_url:
            lines.append("## サムネイル\n")
            lines.append(f"![Thumbnail]({program.thumbnail_url})\n")
        
        # Description
        if program.description:
            lines.append("## 番組説明\n")
            lines.append(f"{program.description}\n")
        
        # Episodes
        if program.episodes:
            lines.append("## エピソード一覧\n")
            
            # Separate regular episodes (< 100) and special episodes (>= 100)
            regular_episodes = [ep for ep in program.episodes if ep.number < 100]
            special_episodes = [ep for ep in program.episodes if ep.number >= 100]
            
            downloadable_count = sum(1 for ep in regular_episodes if ep.is_downloadable)
            premium_count = sum(1 for ep in regular_episodes if ep.is_premium_only)
            
            lines.append(f"- 通常エピソード: {len(regular_episodes)}話")
            lines.append(f"- DL可能: {downloadable_count}話")
            lines.append(f"- プレミアム限定: {premium_count}話")
            if special_episodes:
                lines.append(f"- 特別エピソード (PV等): {len(special_episodes)}話")
            lines.append("")
            
            # Regular episodes table
            if regular_episodes:
                lines.append("### 通常エピソード\n")
                lines.append("| DL可否 | 話数 | タイトル |")
                lines.append("|--------|------|----------|")
                
                for ep in sorted(regular_episodes, key=lambda x: x.number):
                    dl_status = "✅" if ep.is_downloadable else "🔒"
                    lines.append(f"| {dl_status} | {ep.number:02d} | {ep.title} |")
                
                lines.append("")
            
            # Special episodes table
            if special_episodes:
                lines.append("### 特別エピソード (PV等)\n")
                lines.append("| DL可否 | 話数 | タイトル |")
                lines.append("|--------|------|----------|")
                
                for ep in sorted(special_episodes, key=lambda x: x.number):
                    dl_status = "✅" if ep.is_downloadable else "🔒"
                    lines.append(f"| {dl_status} | {ep.number:02d} | {ep.title} |")
                
                lines.append("")
        
        # Footer
        lines.append("---\n")
        lines.append("_Generated by abm_check_")
        
        return "\n".join(lines)
    
    def save_program_md(self, program: Program, output_dir: str = "output") -> Path:
        """
        Save program information as Markdown file.
        
        Args:
            program: Program object
            output_dir: Base directory for output
            
        Returns:
            Path to saved file
        """
        program_dir = Path(output_dir) / program.id
        program_dir.mkdir(parents=True, exist_ok=True)
        
        md_content = self.generate_program_md(program)
        
        md_file = program_dir / "program.md"
        md_file.write_text(md_content, encoding='utf-8')
        
        return md_file
